from pathlib import Path
import pandas as pd

ROOT = Path(__file__).parent
OUT = ROOT / 'outputs'

# Read key inputs
summary = OUT / 'insights.txt'
transfer = OUT / 'transfer_plan.csv'

html_out = OUT / 'executive_brief.html'

ins_text = summary.read_text() if summary.exists() else ''
trans_df = pd.read_csv(transfer) if transfer.exists() else pd.DataFrame()

# Build a simple HTML one-pager
html = []
html.append('<html><head><meta charset="utf-8"><title>Executive Brief — PWA Product Reallocation</title></head><body>')
html.append('<h1>Executive Brief — Reallocation Pilot</h1>')
html.append('<h2>Key insights</h2>')
html.append('<pre style="font-size:14px">')
html.append(ins_text)
html.append('</pre>')

html.append('<h2>Top recommended transfers (pilot)</h2>')
if not trans_df.empty:
    pilot = trans_df.groupby('to_county').sum().reset_index().sort_values('units', ascending=False).head(5)
    html.append(pilot.to_html(index=False))
else:
    html.append('<p>No transfer plan found. Run transfer_plan.py first.</p>')

html.append('<h2>Operational notes</h2>')
html.append('<ul>')
html.append('<li>Validate product mix and expiry before shipment.</li>')
html.append('<li>Start pilot with KISII -> GARISSA and KISII -> TURKANA (largest surplus to largest deficits).</li>')
html.append('<li>Keep 10% buffer in donor counties unless otherwise approved by logistics.</li>')
html.append('</ul>')

html.append('<p>Generated by the PWA distribution analysis pipeline.</p>')
html.append('</body></html>')

html_out.write_text('\n'.join(html), encoding='utf-8')
print('Wrote', html_out)
print('Open it and ' + ('use a browser Print -> Save as PDF' if html_out.exists() else 'generate the transfer plan first'))
